###
GET http://localhost:4004/odata/v4/usage-plugin
Authorization: Basic alice:
###
GET http://localhost:4004/odata/v4/usage-plugin/UsageData
Authorization: Basic alice:
###
POST http://localhost:4004/odata/v4/usage-plugin/UsageData
Authorization: Basic alice:
Content-Type: application/json

{
  "type": "cpu",
  "usage": 19.33
}

###
POST http://localhost:4004/odata/v4/usage-plugin/UsageData
Authorization: Basic alice:
Content-Type: application/json

{
  "type": "memory",
  "usage": 128
}

###
POST http://localhost:4004/odata/v4/usage-plugin/SystemStatus
Authorization: Basic alice:
Content-Type: application/json

{
  "category": "cpu",
  "name": "usage",
  "value": "19.33",
  "numericValue": 19.33,
  "unit": "%",
  "status": "normal"
}